services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: postgres-for-nodejs-service
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pgconf:/etc/postgresql
      - ./pglog:/var/log/postgresql
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rsschool-nodejs-service
    restart: always
    environment:
      - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./src
          target: ./app/src
        - action: rebuild
          path: package.json
