services:
  db:
    image: postgres:bullseye
    container_name: db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_PORT=${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - backend

    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pglogs:/var/logs/postgresql/postgresql.logs
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U admin' ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    restart: always
    container_name: app
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - ${PORT}:${PORT}
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma

networks:
  backend:
    name: backend
    driver: bridge